openapi: 3.0.0
info:
  title: DevContext AI API - Schema V2
  description: |
    Production-grade API for GitHub repository analysis with normalized schema.
    
    Features:
    - Normalized database design (10 entities)
    - Cost tracking per analysis
    - Complete audit trail
    - User progress tracking
    - Interview session management
    - Paginated responses
    
  version: 2.0.0
  contact:
    name: DevContext AI Team
    email: support@devcontext.ai

servers:
  - url: https://2jhc5i9ex2.execute-api.ap-southeast-1.amazonaws.com/prod
    description: Production API (AWS Singapore)
  - url: https://api.devcontext.ai/dev
    description: Development environment
  - url: http://localhost:3000/v2
    description: Local development

tags:
  - name: Analysis
    description: Repository analysis operations
  - name: Interview
    description: Interview practice and session management
  - name: User
    description: User profile and progress
  - name: Export
    description: Report export operations

security:
  - CognitoAuth: []

paths:
  # ============================================================================
  # ANALYSIS ENDPOINTS
  # ============================================================================
  
  /analyze:
    post:
      tags:
        - Analysis
      summary: Initiate repository analysis
      description: |
        Submit a GitHub repository URL for comprehensive analysis.
        
        The analysis includes:
        - Repository metadata extraction
        - Project review (code quality, employability)
        - Intelligence report (architecture, design decisions)
        - Interview question generation
        
        Returns immediately with analysisId for tracking progress.
      operationId: analyzeRepository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequest'
            examples:
              publicRepo:
                summary: Public repository
                value:
                  repositoryUrl: "https://github.com/facebook/react"
              privateRepo:
                summary: Private repository (future)
                value:
                  repositoryUrl: "https://github.com/user/private-repo"
                  githubToken: "ghp_xxxxxxxxxxxx"
      responses:
        '200':
          description: Analysis initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/RateLimitExceeded'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /analyses:
    get:
      tags:
        - Analysis
      summary: List user's analyses
      description: |
        Get paginated list of all analyses for the authenticated user.
        Results are sorted by creation date (most recent first).
      operationId: listAnalyses
      parameters:
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: cursor
          in: query
          description: Pagination cursor from previous response
          schema:
            type: string
        - name: status
          in: query
          description: Filter by analysis status
          schema:
            type: string
            enum: [initiated, processing, completed, failed, cancelled]
      responses:
        '200':
          description: Analyses retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAnalysesResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /analysis/{analysisId}:
    get:
      tags:
        - Analysis
      summary: Get complete analysis
      description: |
        Retrieve full analysis results including:
        - Analysis metadata
        - Repository metadata
        - Project review
        - Intelligence report
        - Interview simulation
        
        Uses batch get for optimal performance.
      operationId: getAnalysis
      parameters:
        - $ref: '#/components/parameters/AnalysisId'
      responses:
        '200':
          description: Analysis retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    
    delete:
      tags:
        - Analysis
      summary: Delete analysis
      description: |
        Delete an analysis and all associated data.
        This action cannot be undone.
      operationId: deleteAnalysis
      parameters:
        - $ref: '#/components/parameters/AnalysisId'
      responses:
        '204':
          description: Analysis deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /analysis/{analysisId}/status:
    get:
      tags:
        - Analysis
      summary: Get analysis status
      description: |
        Poll the current status and progress of an analysis.
        Lightweight endpoint for real-time progress tracking.
      operationId: getAnalysisStatus
      parameters:
        - $ref: '#/components/parameters/AnalysisId'
      responses:
        '200':
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /analysis/{analysisId}/events:
    get:
      tags:
        - Analysis
      summary: Get analysis audit log
      description: |
        Retrieve complete audit trail for an analysis.
        Useful for debugging and monitoring.
      operationId: getAnalysisEvents
      parameters:
        - $ref: '#/components/parameters/AnalysisId'
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
      responses:
        '200':
          description: Events retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/AnalysisEvent'
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /analysis/{analysisId}/cost:
    get:
      tags:
        - Analysis
      summary: Get analysis cost breakdown
      description: |
        Retrieve detailed cost information for an analysis.
        Includes Bedrock tokens and Lambda costs.
      operationId: getAnalysisCost
      parameters:
        - $ref: '#/components/parameters/AnalysisId'
      responses:
        '200':
          description: Cost information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostTracking'
        '404':
          $ref: '#/components/responses/NotFound'
